### ISSUE TITLE
support for multiple storage types / storageClass

### ISSUE THREAD

**Issue by ludurr** [chubaofs/chubaofs#1291]
Hi,
first thank you for your support and for such a great project. 
My Question: 
Is it possible to use multiple storage types/ mounts e.g. daemonsets dataNode would use mounts from workernode:
```
/mnt/ssd
/mnt/hdd
````
so the StorageClasses propagated to kubernetes workload would use following storageClasses:
```
cfs-ssd
cfs-hdd
```
Thank you!
Lukas

**Comment by Huweicai** [comment]
First you can create 2 chubaofs clusters with different disk types, then distinguish them with **masterAddr** parameter in StorageClass, and both StorageClasses can use one csi daemonset, do not need to create two.
Such as:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfs-ssd
provisioner: csi.chubaofs.com
parameters:
  masterAddr: chubaofs-ssd-master.chubao.io
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfs-hdd
provisioner: csi.chubaofs.com
parameters:
  masterAddr: chubaofs-hdd-master.chubao.io
  
```
Also you can create 2 crossZone with different disk types under 1 chubaofs cluster, and distinguish them with **crossZone** parameter in StorageClass:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfs-ssd
provisioner: csi.chubaofs.com
parameters:
  masterAddr: chubaofs-common-master.chubao.io
  crossZone: ssdzone
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfs-hdd
provisioner: csi.chubaofs.com
parameters:
  masterAddr: chubaofs-common-master.chubao.io
  crossZone: hddzone
```

Then you can use both ssd and hdd volumes in kubernetes.

**Comment by shuoranliu** [comment]
@ludurr Please let us know if this answers your question. Thanks!

**Comment by ludurr** [comment]
Hi,
definitely that was the answer i was looking for.
Thank you

**Comment by ludurr** [comment]
Hi,
i have created the group of data/meta node in zone=ssd and data/metanode zone=hdd with common master nodes within kubernetes rke2/rancher version `v1.22.4+rke2r1` and storageClass as described by example above.

Then i sent a request PVC with storageClass above, but it fails to create PV with provided PVC.

Any help is welcome or point me to the right resource/docs.
Thank you.


PVC error:
```
  Type     Reason                Age                From                                                                                       Message
  ----     ------                ----               ----                                                                                       -------
  Normal   Provisioning          14s (x6 over 43s)  csi.chubaofs.com_cfs-csi-controller-846544d6d8-kj279_002aa24b-f7a8-4b5d-baa5-58d4d3d69719  External provisioner is provisioning volume for claim "chubaofs/cfs-pvc"
  Warning  ProvisioningFailed    14s (x6 over 43s)  csi.chubaofs.com_cfs-csi-controller-846544d6d8-kj279_002aa24b-f7a8-4b5d-baa5-58d4d3d69719  failed to provision volume with StorageClass "cfs-hdd": rpc error: code = Unknown desc = create volume is failed
  Normal   ExternalProvisioning  4s (x5 over 43s)   persistentvolume-controller                                                                waiting for a volume to be created, either by external provisioner "csi.chubaofs.com" or manually created by system administrator
```



External provisioner error:
``` 
I1223 16:23:34.340118       1 controller.go:1284] provision "chubaofs/cfs-pvc-2" class "cfs-ssd": started

I1223 16:23:34.343024       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"chubaofs", Name:"cfs-pvc-2", UID:"79c48555-f04d-4ab3-a801-26b21f5acc98", APIVersion:"v1", ResourceVersion:"2964989", FieldPath:""}): 
type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "chubaofs/cfs-pvc-2"

W1223 16:23:34.345819       1 controller.go:916] Retrying syncing claim "79c48555-f04d-4ab3-a801-26b21f5acc98", failure 5

E1223 16:23:34.345837       1 controller.go:939] error syncing claim "79c48555-f04d-4ab3-a801-26b21f5acc98": failed to provision volume with StorageClass "cfs-ssd": rpc error: code = Unknown desc = create volume is failed

I1223 16:23:34.345848       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"chubaofs", Name:"cfs-pvc-2", UID:"79c48555-f04d-4ab3-a801-26b21f5acc98", APIVersion:"v1", ResourceVersion:"2964989", FieldPath:""}):
 type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cfs-ssd": rpc error: code = Unknown desc = create volume is failed
 ```

**Comment by Huweicai** [comment]
Parameter 'owner' is required to mark up the volume belongs to whom, you can set it as what you want, such as:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: chubaofs
    meta.helm.sh/release-namespace: chubaofs-helm
  creationTimestamp: "2021-12-23T11:39:34Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cfs-ssd
  resourceVersion: "3015251"
  uid: b3b09ca4-8be5-42bd-91b7-7a44ee153410
parameters:
  **owner: K8SCSICluster01**
  consulAddr: http://consul-service.chubaofs.svc.cluster.local:8500
  crossZone: ssd
  logLevel: error
  masterAddr: master-service.chubaofs.svc.cluster.local:17010
provisioner: csi.chubaofs.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by ludurr** [comment]
Thank for reply! I have added owner with username without creating it in advance and also tried with user created in davance within chubaofs, but neither was working. 



```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: chubaofs
    meta.helm.sh/release-namespace: chubaofs-helm
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cfs-hdd
parameters:
  consulAddr: http://consul-service.chubaofs.svc.cluster.local:8500
  crossZone: hdd
  logLevel: debug
  owner: cfshdduser
  masterAddr: master-service.chubaofs.svc.cluster.local:17010
provisioner: csi.chubaofs.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by ludurr** [comment]
I have found log from chubaofs csi driver. And based on that i have corrected the parameters for StorageClass `zoneName` and `crossZone`
```
E1224 13:32:38.413989      11 cfs_server.go:169] create volume is failed. url(http://master-service.chubaofs.svc.cluster.local:17010/admin/createVol?name=pvc-fb46d723-3469-449c-b628-5cfcbc7e070b&capacity=1&owner=cfsvolssduser&crossZone=ssd&enableToken=false&zoneName=) code=(2), msg:strconv.ParseBool: parsing "ssd": invalid syntax
E1224 13:32:38.414065      11 utils.go:82] GRPC error: create volume is failed
```

Now its provisioning PV, but it failing to attach the PVC to a POD.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: chubaofs
    meta.helm.sh/release-namespace: chubaofs-helm
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cfs-hdd
parameters:
  consulAddr: http://consul-service.chubaofs.svc.cluster.local:8500
  crossZone: "true"
  zoneName: hdd
  logLevel: debug
  owner: cfshdduser
  masterAddr: master-service.chubaofs.svc.cluster.local:17010
provisioner: csi.chubaofs.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by ludurr** [comment]
I am currently solving the issue mountVolume failed:

```
Normal   SuccessfulAttachVolume  8m23s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-28ae69ff-2ffb-4211-a836-1ce216424d81"
  Warning  FailedMount             8m16s  kubelet                  MountVolume.MountDevice failed for volume "pvc-28ae69ff-2ffb-4211-a836-1ce216424d81" : rpc error: code = Internal desc = mount fail, error: exit status 1
  Normal   Pulled                  8m15s  kubelet                  Container image "nginx:1.17.9" already present on machine
  Normal   Created                 8m15s  kubelet                  Created container cfs-csi-demo-1
  Normal   Started                 8m15s  kubelet                  Started container cfs-csi-demo-1
```

**Comment by Huweicai** [comment]
Sorry I  mistook mixing up the parameter 'zoneName' and 'crossZone', you don't need to care about the parameter 'crossZone' at all, it' my fault, try this way:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfs-ssd
provisioner: csi.chubaofs.com
parameters:
  masterAddr: chubaofs-common-master.chubao.io
  zoneName: ssdzone
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfs-hdd
provisioner: csi.chubaofs.com
parameters:
  masterAddr: chubaofs-common-master.chubao.io
  zoneName: hddzone
```
I've testd in my cluster, it works.
